# ==============================================================================
# server.py
# ==============================================================================
# This module acts as the FastAPI backend for the Zero-Trust WASM Sandbox UI.
# It serves the static front-end assets and exposes a Server-Sent Events (SSE)
# endpoint that streams the live execution logs from the Python AI Agent back
# to the browser dashboard in real time.
# ==============================================================================

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, StreamingResponse
import asyncio
import json
from agent import run_agent_loop
import os
from dotenv import load_dotenv

# Load environment variables from .env if present (e.g., API keys for cloud models)
load_dotenv()

# Initialize the FastAPI application
app = FastAPI(title="Zero-Trust WASM Sandbox Dashboard")

# Mount the static directory to serve CSS and JS assets
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/", summary="Serve Dashboard UI")
def get_home():
    """
    Serves the main HTML dashboard.
    This is a simple Vanilla JS/CSS single-page application.
    """
    with open("static/index.html", "r") as f:
        return HTMLResponse(f.read())

@app.get("/api/run", summary="Trigger Agent and Stream Lifecycle Logs")
async def run_sandbox():
    """
    This endpoint triggers the entire AI Pipeline (Agent -> Sandbox Tool -> Worker destruction).
    It uses Server-Sent Events (SSE) to yield log messages to the UI in real time.
    """
    # Create an asynchronous queue to hold log messages as they are generated by the agent.
    queue = asyncio.Queue()

    async def log_callback(step: str, message: str):
        """
        A callback function passed to the agent. Whenever the agent reaches a new
        milestone (like generating code or running the WASM tool), it calls this
        function, which pushes the log into the async queue.
        """
        await queue.put({"step": step, "message": message})

    async def background_runner():
        """
        Runs the agent loop in the background.
        Once finished, it pushes a 'None' sentinel value to the queue to signal
        the SSE generator to terminate the connection gracefully.
        """
        try:
            # Execute the core agent orchestration logic
            await run_agent_loop(log_callback)
        finally:
            # Sentinel object marks the end of the stream
            await queue.put(None)

    # Start the agent execution as a background task so we don't block the endpoint
    asyncio.create_task(background_runner())

    async def event_generator():
        """
        Asynchronous generator that continually consumes messages from the queue
        and formats them according to the Server-Sent Events (SSE) specification.
        """
        while True:
            data = await queue.get()
            if data is None:
                # Reached end of stream; tell the UI we are complete and break the loop.
                yield f"data: {json.dumps({'step': 'complete', 'message': 'Run complete.'})}\n\n"
                break

            # Yield the JSON data formatted as an SSE packet.
            # Notice the double newline \n\n required by the SSE protocol to delineate events.
            yield f"data: {json.dumps(data)}\n\n"

    # Return the generator as a StreamingResponse, keeping the connection open
    return StreamingResponse(event_generator(), media_type="text/event-stream")

if __name__ == "__main__":
    import uvicorn
    # When running strictly during development, host on 127.0.0.1
    uvicorn.run(app, host="127.0.0.1", port=8001)
